# pandas 进阶修炼 ｜早起Python
<br>

**本习题由公众号【早起Python & 可视化图鉴】 原创，转载及其他形式合作请与我们联系（微信号`sshs321`)，未经授权严禁搬运及二次创作，侵权必究！**



本习题基于 `pandas` 版本 `1.1.3`，所有内容应当在 `Jupyter Notebook` 中执行以获得最佳效果。

不同版本之间写法可能会有少许不同，如若碰到此情况，你应该学会如何自行检索解决。

# 1 - 数据加载与存储

是的，常常被忽略的「<font color=#E36C07>**数据加载与存储**</font>」也大有门道且值得作为本套习题的开门之章。

在一次数据分析的过程中，你可能只会读取或存储一两次数据集。

**但若能灵活掌握各项设置，在读取阶段就将数据筛选、匹配、格式指定等操作完成，有时会为我们节省大量时间。**

在本节习题中，我将 pandas 数据分析中常见的数据读取与存储操作进行整理。

<font color=#E36C07>**既可以用于巩固、学习各种操作，也可以作为速查手册使用**</font>。

## 初始化

<br>

该 `Notebook` 版本为**纯习题版**

如果需要答案或者提示，可以微信搜索公众号「早起Python」获取！

## 1-1 数据读取

### 1 读取 Excel 文件

<br>

- 读取当前目录下 `某招聘网站数据.csv` 文件

- 读取当前目录下 `TOP250.xlsx` 文件

**注意**：使用 `pandas` 读取 `CSV` 与 读取 `xlsx` 格式的 `Excel` 文件方法大致相同

因此接下来与 `Excel` 相关的操作均以 `CSV` 格式进行出题。

In [21]:
import pandas as pd
data = pd.read_csv("某招聘网站数据.csv")
print(len(data))
data = pd.read_excel("TOP250.xlsx")

105

### 2 读取 Excel 文件｜指定位置

在大多数情况下，我们会将 `notebook` 和数据源文件放在同一个目录（文件夹下），这样直接使用`pd.read_xxx("文件名")`即可成功读取。
 
但有时需要读取的文件和 `notebook` 不在同一个目录下，这时可以使用绝对路径或者相对本 `notebook` 的路径。

现在请读取本套习题中第二章节下的数据，即 `2 - 个性化显示设置/data.csv`

In [7]:
data = pd.read_csv("../2 - 个性化显示设置/data.csv")

###  3 读取 Excel 文件｜指定行（顺序）
<br>

读取当前目录下 `某招聘网站数据.csv` 文件的 <font color = '#5F5FFC'>前20行</font>

In [27]:
df = pd.read_csv("某招聘网站数据.csv", nrows=20)
len(df)

20

###  4 读取 Excel 文件｜指定行（跳过）
<br>

读取当前目录下 `某招聘网站数据.csv` 文件并<font color = '#5F5FFC'>跳过前20行</font>

In [33]:
df = pd.read_csv("某招聘网站数据.csv", skiprows=[i for i in range(1, 21)])
# df = pd.read_csv("某招聘网站数据.csv", header=20)
len(df)

85

###  5 读取 Excel 文件｜指定行（条件）
<br>

读取当前目录下 `某招聘网站数据.csv` 文件中全部<font color = '#5F5FFC'>偶数行</font>

思考：如果是读取全部奇数行，或者更多满足指定条件的行呢？

In [54]:
df = pd.read_csv("某招聘网站数据.csv")
df1 = df[df.index%2==1]
print(len(df1))

52

In [64]:
# 或者可以用lambda：
df = pd.read_csv("某招聘网站数据.csv", skiprows=lambda x: (x != 0) and not x % 2)  # 偶数行
df = pd.read_csv("某招聘网站数据.csv", skiprows=lambda x: (x != 0) and x % 2)      # 奇数行

### 6 读取 Excel 文件｜指定列（列号）

<br>

**根据指定列号读取**

读取当前目录下 `某招聘网站数据.csv` 文件的第 `1、3、5` 列

In [55]:
df = pd.read_csv("某招聘网站数据.csv")
df.iloc[:, [1,3,5]]

              positionName companySize financeStage
0                     数据分析     50-150人           A轮
1                     数据建模    150-500人           B轮
2                     数据分析     2000人以上         上市公司
3                     数据分析   500-2000人        D轮及以上
4                     数据分析     2000人以上         上市公司
..                     ...         ...          ...
100                  数据分析师   500-2000人           C轮
101                 商业数据分析   500-2000人           C轮
102        奔驰·耀出行-BI数据分析专家    150-500人        不需要融资
103                BI数据分析师     2000人以上         上市公司
104  数据分析专家-LQ(J181203029)     2000人以上        不需要融资

[105 rows x 3 columns]

In [66]:
# 或者可以用usecols
pd.read_csv("某招聘网站数据.csv", usecols=[1,3,5])

              positionName companySize financeStage
0                     数据分析     50-150人           A轮
1                     数据建模    150-500人           B轮
2                     数据分析     2000人以上         上市公司
3                     数据分析   500-2000人        D轮及以上
4                     数据分析     2000人以上         上市公司
..                     ...         ...          ...
100                  数据分析师   500-2000人           C轮
101                 商业数据分析   500-2000人           C轮
102        奔驰·耀出行-BI数据分析专家    150-500人        不需要融资
103                BI数据分析师     2000人以上         上市公司
104  数据分析专家-LQ(J181203029)     2000人以上        不需要融资

[105 rows x 3 columns]

###  7 读取 Excel 文件｜指定列（列名）

<br>

**根据指定列名读取**

读取当前目录下 `某招聘网站数据.csv` 文件的 `positionId、positionName、salary` 列

In [67]:
# df.loc[:, ["positionId","positionName","salary"]]
# 或者同样可以用usecols参数
pd.read_csv("某招聘网站数据.csv", usecols=["positionId","positionName","salary"])

     positionId           positionName  salary
0       6802721                   数据分析   37500
1       5204912                   数据建模   15000
2       6877668                   数据分析    3500
3       6496141                   数据分析   45000
4       6467417                   数据分析   30000
..          ...                    ...     ...
100     6884346                  数据分析师   25000
101     6849100                 商业数据分析   35000
102     6803432        奔驰·耀出行-BI数据分析专家   30000
103     6704835                BI数据分析师   20000
104     6728058  数据分析专家-LQ(J181203029)   21500

[105 rows x 3 columns]

###  8 读取 Excel 文件｜指定列（匹配）

<br>

**根据指定列名匹配读取**

让我们来个更难一点的，还是读取 `某招聘网站数据.csv` 文件，但现在有一个 list 中包含多个字段👇

`usecols = ['positionId','test','positionName', 'test1','salary']`

如果 `usecols` 中的列名存在于 `某招聘网站数据.csv` 中，则读取。

In [69]:
usecols = ['positionId', 'test', 'positionName', 'test1', 'salary']
pd.read_csv("某招聘网站数据.csv", usecols=lambda c: c in usecols)

     positionId           positionName  salary
0       6802721                   数据分析   37500
1       5204912                   数据建模   15000
2       6877668                   数据分析    3500
3       6496141                   数据分析   45000
4       6467417                   数据分析   30000
..          ...                    ...     ...
100     6884346                  数据分析师   25000
101     6849100                 商业数据分析   35000
102     6803432        奔驰·耀出行-BI数据分析专家   30000
103     6704835                BI数据分析师   20000
104     6728058  数据分析专家-LQ(J181203029)   21500

[105 rows x 3 columns]

### 9 读取 Excel 文件｜指定索引

<br>

读取当前目录下 `某招聘网站数据.csv` 文件，并在读取时将 `positionId` 设置为索引列

In [70]:
pd.read_csv("某招聘网站数据.csv", index_col="positionId")

,positionName,companyId,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,skillLables,...,plus,pcShow,appShow,deliver,gradeDescription,promotionScoreExplain,isHotHire,count,aggregatePositionIds,famousCompany
positionId,,,,,,,,,,,,,,,,,,,,,
6802721,数据分析,475770,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,"['SQL', '数据库', '数据运营', 'BI']",...,NaN,0,0,0,NaN,NaN,0,0,[],False
5204912,数据建模,50735,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,"['算法', '数据架构']",...,NaN,0,0,0,NaN,NaN,0,0,[],False
6877668,数据分析,100125,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,"['数据库', '数据分析', 'SQL']",...,NaN,0,0,0,NaN,NaN,0,0,[],False
6496141,数据分析,26564,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,[],...,NaN,0,0,0,NaN,NaN,0,0,[],True
6467417,数据分析,29211,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,"['BI', '数据分析', '数据运营']",...,NaN,0,0,0,NaN,NaN,0,0,[],True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6884346,数据分析师,21236,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,"['数据库', '商业', '数据分析', 'SQL']",...,NaN,0,0,0,NaN,NaN,0,0,[],False
6849100,商业数据分析,72076,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,"['市场', '数据分析', '行业分析', '市场分析']",...,NaN,0,0,0,NaN,NaN,0,0,[],False
6803432,奔驰·耀出行-BI数据分析专家,751158,150-500人,移动互联网,不需要融资,[],开发|测试|运维类,数据开发,数据分析,"['MySQL', '数据处理', '数据分析']",...,NaN,0,0,0,NaN,NaN,0,0,[],False
6704835,BI数据分析师,52840,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,"['SQLServer', '数据分析']",...,NaN,0,0,0,NaN,NaN,0,0,[],True
6728058,数据分析专家-LQ(J181203029),2474,2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,[],...,NaN,0,0,0,NaN,NaN,0,0,[],True

###  10 读取 Excel 文件｜指定标题

<br>


读取当前目录下 `某招聘网站数据.csv` 文件的 `positionId、positionName、salary` 列，并将标题设置为 `ID、岗位名称、薪资`

In [84]:
pd.read_csv(
    "某招聘网站数据.csv",
    header=0,
    usecols=["positionId", "positionName", "salary"],
#     names=["ID", "岗位名称", "薪资"]
).rename(columns={"positionId": "ID", "positionName":"岗位名称","salary":"薪资"})

          ID                   岗位名称     薪资
0    6802721                   数据分析  37500
1    5204912                   数据建模  15000
2    6877668                   数据分析   3500
3    6496141                   数据分析  45000
4    6467417                   数据分析  30000
..       ...                    ...    ...
100  6884346                  数据分析师  25000
101  6849100                 商业数据分析  35000
102  6803432        奔驰·耀出行-BI数据分析专家  30000
103  6704835                BI数据分析师  20000
104  6728058  数据分析专家-LQ(J181203029)  21500

[105 rows x 3 columns]

###  11 读取 Excel 文件｜缺失值转换

<br>


读取当前目录下 `某招聘网站数据.csv` 文件，**并不将缺失值标记为 `NA`**

思考：为什么要这样做？

In [88]:
pd.read_csv("某招聘网站数据.csv", keep_default_na=False)

,positionId,positionName,companyId,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,...,plus,pcShow,appShow,deliver,gradeDescription,promotionScoreExplain,isHotHire,count,aggregatePositionIds,famousCompany
0,6802721,数据分析,475770,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],False
1,5204912,数据建模,50735,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,...,,0,0,0,,,0,0,[],False
2,6877668,数据分析,100125,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],False
3,6496141,数据分析,26564,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,...,,0,0,0,,,0,0,[],True
4,6467417,数据分析,29211,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,6884346,数据分析师,21236,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],False
101,6849100,商业数据分析,72076,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,...,,0,0,0,,,0,0,[],False
102,6803432,奔驰·耀出行-BI数据分析专家,751158,150-500人,移动互联网,不需要融资,[],开发|测试|运维类,数据开发,数据分析,...,,0,0,0,,,0,0,[],False
103,6704835,BI数据分析师,52840,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,...,,0,0,0,,,0,0,[],True
104,6728058,数据分析专家-LQ(J181203029),2474,2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,...,,0,0,0,,,0,0,[],True

###  12 读取 Excel 文件｜缺失值标记

<br>


读取当前目录下 `某招聘网站数据.csv` 文件，**并将`[]`标记为缺失值**

In [89]:
pd.read_csv("某招聘网站数据.csv", na_values=["[]"])

,positionId,positionName,companyId,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,...,plus,pcShow,appShow,deliver,gradeDescription,promotionScoreExplain,isHotHire,count,aggregatePositionIds,famousCompany
0,6802721,数据分析,475770,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,False
1,5204912,数据建模,50735,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,...,NaN,0,0,0,NaN,NaN,0,0,NaN,False
2,6877668,数据分析,100125,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,False
3,6496141,数据分析,26564,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,True
4,6467417,数据分析,29211,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,6884346,数据分析师,21236,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,False
101,6849100,商业数据分析,72076,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,False
102,6803432,奔驰·耀出行-BI数据分析专家,751158,150-500人,移动互联网,不需要融资,NaN,开发|测试|运维类,数据开发,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,False
103,6704835,BI数据分析师,52840,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,True
104,6728058,数据分析专家-LQ(J181203029),2474,2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,...,NaN,0,0,0,NaN,NaN,0,0,NaN,True

### 13 读取 Excel 文件｜忽略缺失值

<br>

读取当前目录下 `某招聘网站数据.csv` 文件，**但不处理缺失值**

思考：和之前的有什么不同，为什么这么做？

In [91]:
pd.read_csv("某招聘网站数据.csv", na_filter=False)

,positionId,positionName,companyId,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,...,plus,pcShow,appShow,deliver,gradeDescription,promotionScoreExplain,isHotHire,count,aggregatePositionIds,famousCompany
0,6802721,数据分析,475770,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],False
1,5204912,数据建模,50735,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,...,,0,0,0,,,0,0,[],False
2,6877668,数据分析,100125,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],False
3,6496141,数据分析,26564,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,...,,0,0,0,,,0,0,[],True
4,6467417,数据分析,29211,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,6884346,数据分析师,21236,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,...,,0,0,0,,,0,0,[],False
101,6849100,商业数据分析,72076,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,...,,0,0,0,,,0,0,[],False
102,6803432,奔驰·耀出行-BI数据分析专家,751158,150-500人,移动互联网,不需要融资,[],开发|测试|运维类,数据开发,数据分析,...,,0,0,0,,,0,0,[],False
103,6704835,BI数据分析师,52840,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,...,,0,0,0,,,0,0,[],True
104,6728058,数据分析专家-LQ(J181203029),2474,2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,...,,0,0,0,,,0,0,[],True

### 14 读取 Excel 文件｜指定格式

<br>

读取当前目录下 `某招聘网站数据.csv` 文件，并将 `positionId,companyId` 设置为字符串格式

In [100]:
df1 = pd.read_csv("某招聘网站数据.csv", dtype={"positionId":str,"companyId":str})
type(df1["positionId"][0])

str

### 15 读取 Excel 文件｜指定格式（时间）

<br>

读取当前目录下 `某招聘网站数据.csv` 文件，并将 `createTime` 列设置为字符串格式

In [115]:
df1 = pd.read_csv("某招聘网站数据.csv", 
                  parse_dates=["createTime"]
                # parse_dates=True
                  )
type(df1["createTime"][0])
# df1["createTime"][0]

pandas._libs.tslibs.timestamps.Timestamp

### 16 读取 Excel 文件｜分块读取


<br>

读取当前目录下 `某招聘网站数据.csv` 文件，要求返回一个可迭代对象，每次读取 10 行

思考：为什么这样做？

In [129]:
df = pd.read_csv("某招聘网站数据.csv", chunksize=10)

for data in df:
    print(data)

   positionId positionName  companyId companySize industryField financeStage  \
0     6802721         数据分析     475770     50-150人      移动互联网,电商           A轮
1     5204912         数据建模      50735    150-500人            电商           B轮
2     6877668         数据分析     100125     2000人以上    移动互联网,企业服务         上市公司
3     6496141         数据分析      26564   500-2000人            电商        D轮及以上
4     6467417         数据分析      29211     2000人以上         物流丨运输         上市公司
5     6882347         数据分析      94826     50-150人      移动互联网,社交           B轮
6     6841659         数据分析     348784     50-150人      移动互联网,电商           A轮
7     6764018      数据建模工程师      13163   500-2000人         移动互联网         上市公司
8     6458372       数据分析专家      34132    150-500人     数据服务,广告营销           A轮
9     6786904        数据分析师      13163   500-2000人         移动互联网         上市公司

                      companyLabelList  firstType secondType thirdType  ...  \
0     ['绩效奖金', '带薪年假', '定期体检', '弹性工作']  产品|需求|项目类       数据分析      数据分析  ...
1     ['年终奖金', '做五休二', '六险一金', '子女福利']  开发|测试|运维类       数据开发        建模  ...
2     ['节日礼物', '年底双薪', '股票期权', '带薪年假']  产品|需求|项目类       数据分析      数据分析  ...
3    ['生日趴', '每月腐败基金', '每月补贴', '年度旅游']  开发|测试|运维类       数据开发      数据分析  ...
4     ['技能培训', '免费班车', '专项奖金', '岗位晋升']  产品|需求|项目类       数据分析      数据分析  ...
5     ['股票期权', '扁平管理', '五险一金', '岗位晋升']  产品|需求|项目类       数据分析      数据分析  ...
6     ['大牛团队', '扁平管理', '年底双薪', '股票期权']  产品|需求|项目类       数据分析      数据分析  ...
7     ['绩效奖金', '股票期权', '年底双薪', '专项奖金']  开发|测试|运维类       数据开发        建模  ...
8  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  产品|需求|项目类       数据分析    其他数据分析  ...
9     ['绩效奖金', '股票期权', '年底双薪', '专项奖金']  开发|测试|运维类       数据开发     BI工程师  ...

  plus pcShow appShow deliver gradeDescription promotionScoreExplain  \
0  NaN      0       0       0              NaN                   NaN
1  NaN      0       0       0              NaN                   NaN
2  NaN      0       0       0              NaN                   NaN
3  NaN      0       0       0              NaN                   NaN
4  NaN      0       0       0              NaN                   NaN
5  NaN      0       0       0              NaN                   NaN
6  NaN      0       0       0              NaN                   NaN
7  NaN      0       0       0              NaN                   NaN
8  NaN      0       0       0              NaN                   NaN
9  NaN      0       0       0              NaN                   NaN

  isHotHire  count aggregatePositionIds famousCompany
0         0      0                   []         False
1         0      0                   []         False
2         0      0                   []         False
3         0      0                   []          True
4         0      0                   []          True
5         0      0                   []         False
6         0      0                   []         False
7         0      0                   []          True
8         0      0                   []         False
9         0      0                   []          True

[10 rows x 52 columns]
    positionId      positionName  companyId companySize industryField  \
10     6804629             数据分析师      34132    150-500人     数据服务,广告营销
11     6847013  大数据分析工程师(J11108)      55046     2000人以上    移动互联网,企业服务
12     6763962           数据分析工程师      13163   500-2000人         移动互联网
13     6804489           资深数据分析师      34132    150-500人     数据服务,广告营销
14     6657285             数据分析师       7461     2000人以上          企业服务
15     6882983       产品运营（偏数据分析）       7461     2000人以上          企业服务
16     6486988       资深数据分析师（杭州）       7461     2000人以上          企业服务
17     5519962           大数据建模总监      50735    150-500人            电商
18     5559894   数据建模专家-杭州-01546       6502   500-2000人     信息安全,数据服务
19     6702852      数据分析专家（游戏业务）        593     2000人以上      移动互联网,游戏

   financeStage                     companyLabelList  firstType secondType  \
10           A轮  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  产品|需求|项目类       数据分析
11         上市公司     ['技能培训', '年底双薪', '带薪年假', '岗位晋升']  开发|测试|运维类       数据开发
12         上市公司     ['绩效奖金', '股票期权', '年底双薪', '专项奖金']  开发|测试|运维类       数据开发
13           A轮  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  开发|测试|运维类       数据开发
14         上市公司   ['工程师氛围', '弹性工作', '扁平管理', '上班不打卡']  产品|需求|项目类       数据分析
15         上市公司   ['工程师氛围', '弹性工作', '扁平管理', '上班不打卡']  运营|编辑|客服类         运营
16         上市公司   ['工程师氛围', '弹性工作', '扁平管理', '上班不打卡']  开发|测试|运维类       数据开发
17           B轮     ['年终奖金', '做五休二', '六险一金', '子女福利']  开发|测试|运维类       数据开发
18        D轮及以上     ['技能培训', '股票期权', '绩效奖金', '岗位晋升']  开发|测试|运维类       数据开发
19        不需要融资     ['五险一金', '交通补助', '绩效奖金', '节日礼物']  开发|测试|运维类       数据开发

   thirdType  ... plus pcShow appShow deliver gradeDescription  \
10      数据分析  ...  NaN      0       0       0              NaN
11      数据分析  ...  NaN      0       0       0              NaN
12      数据分析  ...  NaN      0       0       0              NaN
13      数据分析  ...  NaN      0       0       0              NaN
14      数据分析  ...  NaN      0       0       0              NaN
15      数据运营  ...  NaN      0       0       0              NaN
16      数据分析  ...  NaN      0       0       0              NaN
17        建模  ...  NaN      0       0       0              NaN
18        建模  ...  NaN      0       0       0              NaN
19      数据分析  ...  NaN      0       0       0              NaN

   promotionScoreExplain isHotHire  count aggregatePositionIds famousCompany
10                   NaN         0      0                   []         False
11                   NaN         0      0                   []         False
12                   NaN         0      0                   []          True
13                   NaN         0      0                   []         False
14                   NaN         0      0                   []          True
15                   NaN         0      0                   []          True
16                   NaN         0      0                   []          True
17                   NaN         0      0                   []         False
18                   NaN         0      0                   []         False
19                   NaN         0      0                   []          True

[10 rows x 52 columns]
    positionId positionName  companyId companySize industryField financeStage  \
20     6829277      资深数据分析师        593     2000人以上      移动互联网,游戏        不需要融资
21     6267370       数据分析专家      31544    150-500人          数据服务        不需要融资
22     5927901       数据分析经理         62     2000人以上         文娱丨内容           C轮
23     6862245       数据分析专家     473950     50-150人         移动互联网          未融资
24     5604926        数据分析师     143884     50-150人      移动互联网,金融           A轮
25     6601086        数据分析师      21187    150-500人    企业服务,移动互联网          天使轮
26     6850849       数据分析专家     255742    150-500人         金融,电商           C轮
27     5520623       数据分析经理      19875     2000人以上            硬件        不需要融资
28     6657704        数据分析师     165220    150-500人            社交        不需要融资
29     6234992        数据分析师        542   500-2000人          消费生活        D轮及以上

                        companyLabelList  firstType secondType thirdType  ...  \
20      ['五险一金', '交通补助', '绩效奖金', '节日礼物']  产品|需求|项目类     高端产品职位    数据分析专家  ...
21    ['专业红娘牵线', '节日礼物', '技能培训', '岗位晋升']  开发|测试|运维类       数据开发      数据分析  ...
22  ['扁平管理', '弹性工作', '大厨定制三餐', '就近租房补贴']  产品|需求|项目类       产品经理    其他产品经理  ...
23                                    []  产品|需求|项目类       数据分析      数据分析  ...
24      ['股票期权', '带薪年假', '绩效奖金', '年底双薪']  开发|测试|运维类       数据开发      数据分析  ...
25       ['带薪年假', '年轻团队', '股票期权', '下午茶']  产品|需求|项目类       数据分析      数据分析  ...
26   ['持牌金融机构', '跨境支付', '跨境金融', '国际化团队']  开发|测试|运维类       数据开发      数据分析  ...
27      ['年终分红', '带薪年假', '年度旅游', '岗位晋升']  产品|需求|项目类       数据分析      数据分析  ...
28      ['绩效奖金', '带薪年假', '交通补助', '午餐补助']  产品|需求|项目类       数据分析      数据分析  ...
29      ['六险一金', '快乐高效文化', '绩效奖金', '信任']  产品|需求|项目类       数据分析      数据分析  ...

   plus pcShow appShow deliver gradeDescription promotionScoreExplain  \
20  NaN      0       0       0              NaN                   NaN
21  NaN      0       0       0              NaN                   NaN
22  NaN      0       0       0              NaN                   NaN
23  NaN      0       0       0              NaN                   NaN
24  NaN      0       0       0              NaN                   NaN
25  NaN      0       0       0              NaN                   NaN
26  NaN      0       0       0              NaN                   NaN
27  NaN      0       0       0              NaN                   NaN
28  NaN      0       0       0              NaN                   NaN
29  NaN      0       0       0              NaN                   NaN

   isHotHire  count aggregatePositionIds famousCompany
20         0      0                   []          True
21         0      0                   []         False
22         0      0                   []          True
23         0      0                   []         False
24         0      0                   []         False
25         0      0                   []         False
26         0      0                   []         False
27         0      0                   []          True
28         0      0                   []         False
29         0      0                   []          True

[10 rows x 52 columns]
    positionId positionName  companyId companySize industryField financeStage  \
30     6234992        数据分析师        542   500-2000人          消费生活        D轮及以上
31     6758467      店铺数据分析师      80863    150-500人      移动互联网,电商           B轮
32     6804489      资深数据分析师      34132    150-500人     数据服务,广告营销           A轮
33     6764017    数据分析师（社招）      13163   500-2000人         移动互联网         上市公司
34     6228290      商业数据分析师     509360     50-150人    移动互联网,企业服务           B轮
35     6284662      bi数据分析师      50354     2000人以上         物流丨运输        D轮及以上
36     6886661      浙江数据分析师     321001    150-500人       金融,数据服务        D轮及以上
37     6242470        数据分析师      31544    150-500人          数据服务        不需要融资
38     6601086        数据分析师      21187    150-500人    企业服务,移动互联网          天使轮
39     6569491        数据分析师     231698     50-150人    移动互联网,数据服务        不需要融资

                       companyLabelList  firstType secondType thirdType  ...  \
30     ['六险一金', '快乐高效文化', '绩效奖金', '信任']  产品|需求|项目类       数据分析      数据分析  ...
31     ['技能培训', '带薪年假', '绩效奖金', '岗位晋升']     市场|商务类      市场|营销    商业数据分析  ...
32  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  开发|测试|运维类       数据开发      数据分析  ...
33     ['绩效奖金', '股票期权', '年底双薪', '专项奖金']  产品|需求|项目类       数据分析      数据分析  ...
34        ['定期体检', '帅哥多', '领导好', '美女多']     市场|商务类      市场|营销    商业数据分析  ...
35     ['技能培训', '节日礼物', '年底双薪', '带薪年假']  开发|测试|运维类       数据开发     BI工程师  ...
36     ['年底双薪', '午餐补助', '年终分红', '绩效奖金']  开发|测试|运维类       数据开发      数据分析  ...
37   ['专业红娘牵线', '节日礼物', '技能培训', '岗位晋升']  产品|需求|项目类       数据分析      数据分析  ...
38      ['带薪年假', '年轻团队', '股票期权', '下午茶']  产品|需求|项目类       数据分析      数据分析  ...
39     ['年底双薪', '定期体检', '午餐补助', '交通补助']  产品|需求|项目类       数据分析      数据分析  ...

   plus pcShow appShow deliver gradeDescription promotionScoreExplain  \
30  NaN      0       0       0              NaN                   NaN
31  NaN      0       0       0              NaN                   NaN
32  NaN      0       0       0              NaN                   NaN
33  NaN      0       0       0              NaN                   NaN
34  NaN      0       0       0              NaN                   NaN
35  NaN      0       0       0              NaN                   NaN
36  NaN      0       0       0              NaN                   NaN
37  NaN      0       0       0              NaN                   NaN
38  NaN      0       0       0              NaN                   NaN
39  NaN      0       0       0              NaN                   NaN

   isHotHire  count aggregatePositionIds famousCompany
30         0      0                   []          True
31         0      0                   []         False
32         0      0                   []         False
33         0      0                   []          True
34         0      0                   []         False
35         0      0                   []         False
36         0      0                   []         False
37         0      0                   []         False
38         0      0                   []         False
39         0      0                   []         False

[10 rows x 52 columns]
    positionId positionName  companyId companySize industryField financeStage  \
40     6791055      高级数据分析师     432882    150-500人         移动互联网        不需要融资
41     6869123  数据分析师（财务方向）     173746    150-500人          消费生活           C轮
42     6344146      资深数据分析师     522865    150-500人            游戏        不需要融资
43     5921220      财务数据分析师     137388    150-500人      移动互联网,电商        不需要融资
44     6653757      银行数据分析岗      23403     2000人以上          企业服务         上市公司
45     6684619      金融数据分析师      26564   500-2000人            电商        D轮及以上
46     6228290      商业数据分析师     509360     50-150人    移动互联网,企业服务           B轮
47     6339988     数据分析师/BI     238706    150-500人      电商,移动互联网        不需要融资
48     6067812       数据分析专员      98316     2000人以上       电商,消费生活         上市公司
49     5990647    高级财务数据分析师      18655     2000人以上         汽车丨出行        D轮及以上

                      companyLabelList  firstType secondType thirdType  ...  \
40  ['技术大牛', '领导nice', '帅哥美女', '环境超棒']  产品|需求|项目类       数据分析      数据分析  ...
41                                  []  产品|需求|项目类       数据分析      数据分析  ...
42    ['年底双薪', '专项奖金', '提供三餐', '便捷班车']  开发|测试|运维类       数据开发      数据分析  ...
43    ['年终分红', '绩效奖金', '定期体检', '年底双薪']  综合职能|高级管理         财务      财务风控  ...
44    ['五险一金', '通讯津贴', '带薪年假', '定期体检']  开发|测试|运维类       数据开发      数据分析  ...
45   ['生日趴', '每月腐败基金', '每月补贴', '年度旅游']  开发|测试|运维类       数据开发      数据分析  ...
46       ['定期体检', '帅哥多', '领导好', '美女多']     市场|商务类      市场|营销    商业数据分析  ...
47    ['年底双薪', '绩效奖金', '带薪年假', '定期体检']  开发|测试|运维类       数据开发      数据分析  ...
48    ['午餐补助', '带薪年假', '定期体检', '年度旅游']  产品|需求|项目类       数据分析      数据分析  ...
49      ['技能培训', 'Geek', '开放', '扁平管理']  综合职能|高级管理         财务        财务  ...

   plus pcShow appShow deliver gradeDescription promotionScoreExplain  \
40  NaN      0       0       0              NaN                   NaN
41  NaN      0       0       0              NaN                   NaN
42  NaN      0       0       0              NaN                   NaN
43  NaN      0       0       0              NaN                   NaN
44  NaN      0       0       0              NaN                   NaN
45  NaN      0       0       0              NaN                   NaN
46  NaN      0       0       0              NaN                   NaN
47  NaN      0       0       0              NaN                   NaN
48  NaN      0       0       0              NaN                   NaN
49  NaN      0       0       0              NaN                   NaN

   isHotHire  count aggregatePositionIds famousCompany
40         0      0                   []         False
41         0      0                   []         False
42         0      0                   []         False
43         0      0                   []         False
44         0      0                   []         False
45         0      0                   []          True
46         0      0                   []         False
47         0      0                   []         False
48         0      0                   []         False
49         0      0                   []          True

[10 rows x 52 columns]
    positionId        positionName  companyId companySize industryField  \
50     6680900    数据分析师 (MJ000250)     114335    150-500人          数据服务
51     6191993     数据分析专家03-10-217      18655     2000人以上         汽车丨出行
52     6486069        解决方案顾问/数据分析师     166666    150-500人     企业服务,数据服务
53     6814233               数据分析师     619746     2000人以上            教育
54     6046775              数据分析专家     133429     50-150人    移动互联网,消费生活
55     6791055             高级数据分析师     432882    150-500人         移动互联网
56     6037742  资深数据分析师 (MJ000088)     127233    150-500人          电子商务
57     6872125               数据分析师     172552   500-2000人          消费生活
58     5921220             财务数据分析师     137388    150-500人      移动互联网,电商
59     5453691             数据分析实习生     166666    150-500人     企业服务,数据服务

   financeStage                    companyLabelList  firstType secondType  \
50           B轮     ['股票期权', '弹性工作', '领导好', '五险一金']  产品|需求|项目类       产品经理
51        D轮及以上      ['技能培训', 'Geek', '开放', '扁平管理']  开发|测试|运维类       数据开发
52           B轮    ['股票期权', '绩效奖金', '带薪年假', '弹性工作']  产品|需求|项目类       数据分析
53         上市公司    ['绩效奖金', '定期体检', '提供宿舍', '管理规范']  产品|需求|项目类       数据分析
54          未融资     ['年底双薪', '专项奖金', '美女多', '弹性工作']  产品|需求|项目类     高端产品职位
55        不需要融资  ['技术大牛', '领导nice', '帅哥美女', '环境超棒']  产品|需求|项目类       数据分析
56        不需要融资    ['带薪年假', '绩效奖金', '定期体检', '弹性工作']  开发|测试|运维类       数据开发
57        不需要融资                                  []  产品|需求|项目类       数据分析
58        不需要融资    ['年终分红', '绩效奖金', '定期体检', '年底双薪']  综合职能|高级管理         财务
59           B轮    ['股票期权', '绩效奖金', '带薪年假', '弹性工作']  开发|测试|运维类       数据开发

   thirdType  ... plus pcShow appShow deliver gradeDescription  \
50     数据分析师  ...  NaN      0       0       0              NaN
51      数据分析  ...  NaN      0       0       0              NaN
52      数据分析  ...  NaN      0       0       0              NaN
53      数据分析  ...  NaN      0       0       0              NaN
54    数据分析专家  ...  NaN      0       0       0              NaN
55      数据分析  ...  NaN      0       0       0              NaN
56      数据分析  ...  NaN      0       0       0              NaN
57      数据分析  ...  NaN      0       0       0              NaN
58      财务风控  ...  NaN      0       0       0              NaN
59      数据分析  ...  NaN      0       0       0              NaN

   promotionScoreExplain isHotHire  count aggregatePositionIds famousCompany
50                   NaN         0      0                   []         False
51                   NaN         0      0                   []          True
52                   NaN         0      0                   []         False
53                   NaN         0      0                   []         False
54                   NaN         0      0                   []         False
55                   NaN         0      0                   []         False
56                   NaN         0      0                   []         False
57                   NaN         0      0                   []         False
58                   NaN         0      0                   []         False
59                   NaN         0      0                   []         False

[10 rows x 52 columns]
    positionId         positionName  companyId companySize industryField  \
60     5978750    数据分析师（保险）13-01-19      18655     2000人以上         汽车丨出行
61     5990647            高级财务数据分析师      18655     2000人以上         汽车丨出行
62     6191993      数据分析专家03-10-217      18655     2000人以上         汽车丨出行
63     6680900     数据分析师 (MJ000250)     114335    150-500人          数据服务
64     6789831              数据分析实习生     306282    150-500人    移动互联网,数据服务
65     6486069         解决方案顾问/数据分析师     166666    150-500人     企业服务,数据服务
66     6848382  资深数据分析师（商品方向）G01053     179243   500-2000人      电商,移动互联网
67     5203054              资深数据分析师        329     2000人以上            电商
68     6829736     数据分析负责人 or 数据分析师     205347     2000人以上         金融,电商
69     6116460  资深数据分析/数据分析专家G00796     179243   500-2000人      电商,移动互联网

   financeStage                  companyLabelList  firstType secondType  \
60        D轮及以上    ['技能培训', 'Geek', '开放', '扁平管理']  开发|测试|运维类       数据开发
61        D轮及以上    ['技能培训', 'Geek', '开放', '扁平管理']  综合职能|高级管理         财务
62        D轮及以上    ['技能培训', 'Geek', '开放', '扁平管理']  开发|测试|运维类       数据开发
63           B轮   ['股票期权', '弹性工作', '领导好', '五险一金']  产品|需求|项目类       产品经理

### 17 读取 txt 文件｜常规

<br>

读取当前目录下 `Titanic.txt` 文件。

注意：在接下来的几种格式文件读取中，对于之前重复的参数/功能将不再整理，仅介绍读取功能。

### 18 读取 txt 文件｜含中文

<br>

读取当前目录下 `TOP250.txt` 文件。

### 19 读取 JSON 文件



<br>

读取当前目录下 `某基金数据.json` 文件。

### 20 读取 HDF5 文件

<br>

`HDF5`是一种特殊的文件格式，常见于在大规模存储数据上

关于 `pandas` 与 `hdf5` 格式文件的操作较多，下面仅学习如何读取。

读取当前目录下`store_tl.h5`文件

微信搜索公众号「早起Python」，关注后可以获得更多资源！

### 21 从剪贴板读取数据

<br>

打开当前目录下 `Titanic.txt` 文件，全选并复制。

现在直接从剪贴板读取数据。

### 22 从 SQL 读取数据

<br>

有时我们需要从 `SQL` 中读取数据，如果先将数据导出再`pandas`读取并不是一个合适的选择。

在 `pandas` 中支持直接从 `sql` 中查询并读取。

为了方便统一操作，请先执行下面的代码创建数据。

In [121]:
from sqlite3 import connect
conn = connect(':memory:')
df = pd.DataFrame(data=[[0, '10/11/12'], [1, '12/11/10']],
                  columns=['int_column', 'date_column'])
df.to_sql('test_data', conn)

下面将 `SQL` 语句 `SELECT int_column, date_column FROM test_data` 转换为 `DataFrame`

   int_column date_column
0           0    10/11/12
1           1    12/11/10

### 23 从网页读取数据

<br>

直接从东京奥运会官网读取奖牌榜数据。

目标网站地址为 `https://olympics.com/tokyo-2020/olympic-games/zh/results/all-sports/medal-standings.htm`

思考：什么类型的在线表格可以直接读取？

### 24 循环读取数据

<br>

在本小节 `demodata` 文件夹下有多个 `Excel` 文件，要求一次性循环读取全部文件

## 1-2 数据创建

<br>

除了直接读取本地文件，学会直接创建数据框也很重要，常见于测试一些函数，下面是从常见数据结构创建数据框的方法整理

### 25 从列表创建

<br>

将下面的 `list` 转换为 `dataframe`，并指定列名为`"早起Python"`

In [137]:
l = [1,2,3,4,5]

### 26 从列表创建｜嵌套列表

<br>

将下面的 `list` 转换为 `dataframe`，并指定行索引为`"公众号","早起Python"`

In [150]:
l = [[1,2,3],[4,5,6]]

![公众号：早起Python](http://liuzaoqi.oss-cn-beijing.aliyuncs.com/2021/09/18/16319660121648.jpg?域名/sample.jpg?x-oss-process=style/stylename)

### 27 从字典创建

执行下方代码，并将字典转换为`dataframe`

In [124]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]) }

### 28 从字典创建｜指定索引

<br>

还是上一题的字典`d`，将其转换为`dataframe`并指定索引顺序为 `d、b、a`

### 29 从字典创建｜指定列名

<br>

还是上一题的字典`d`，将其转换为`dataframe`并指定索引顺序为 `d、b、a`，列名为`"two", "three"`

### 30 从字典创建｜字典列表
<br>

将下方列表型字典转换为`dataframe`

思考：如何指定行/列索引？

In [ ]:
d = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20}]

### 31 从集合创建

<br>

将下面的元组转换为 dataframe 且行列索引均为 `1,2,3,4`

In [163]:
t =((1,0,0,0,),(2,3,0,0,),(4,5,6,0,),(7,8,9,10,))

## 1-3 数据存储

### 32 保存为 CSV

<br>

将第三题读取到的数据保存为 `csv` 格式至当前目录下（文件名任意）

In [184]:
data = pd.read_csv("某招聘网站数据.csv",nrows = 20)

### 33 保存为 CSV｜指定列

<br>

将第三题读取到的数据保存为 `csv` 格式至当前目录下（文件名任意），且只保留`positionName、salary`两列

### 34 保存为 CSV｜取消索引

<br>

将第三题读取到的数据保存为 `csv` 格式至当前目录下（文件名任意），且取消每一行的索引

### 35 保存为 CSV｜标记缺失值

<br>

在上一题的基础上，在保存的同时，将缺失值标记为`'数据缺失'`

### 36 保存为CSV｜压缩

<br>

将上一题的数据保存至 `zip` 文件，解压后出现 `out.csv`

### 37 保存为 Excel 

<br>

将第三题读取到的数据保存为 `xlsx` 格式至当前目录下（文件名任意）

### 38 保存为 JSON

将之前的数据保存为 `json` 格式至当前目录下（文件名任意）

### 39 保存为 Markdown

将之前数据转换为 `markdown` 形式表格，这样可以直接复制进 `.md` 文件中使用

### 40 保存为 Html

将之前的数据保存为 `html` 格式至当前目录下（文件名任意），并进行如下设置
- 取消行索引
- 标题居中对齐
- 列宽100

![](http://liuzaoqi.oss-cn-beijing.aliyuncs.com/2021/09/16/16317972442543.jpg?域名/sample.jpg?x-oss-process=style/stylename)